
# cargo-vet config file

[cargo-vet]
version = "0.10"

[imports.bytecode-alliance]
url = "https://raw.githubusercontent.com/bytecodealliance/wasmtime/main/supply-chain/audits.toml"

[imports.embark-studios]
url = "https://raw.githubusercontent.com/EmbarkStudios/rust-ecosystem/main/audits.toml"

[imports.google]
url = "https://raw.githubusercontent.com/google/supply-chain/main/audits.toml"

[imports.mozilla]
url = "https://raw.githubusercontent.com/mozilla/supply-chain/main/audits.toml"

[policy.gtk-rs-audit]
criteria = "safe-to-run"
notes = "For desktop applications with little no to external exposure safe-to-run should usally be sufficient."

[[exemptions.autocfg]]
version = "1.4.0"
criteria = "safe-to-run"

[[exemptions.block]]
version = "0.1.6"
criteria = "safe-to-run"

[[exemptions.cairo-rs]]
version = "0.20.1"
criteria = "safe-to-run"
suggest = false
notes = "Do not audit gtk-rs itself, but just its dependencies"

[[exemptions.cairo-sys-rs]]
version = "0.20.0"
criteria = "safe-to-run"
suggest = false
notes = "Do not audit gtk-rs itself, but just its dependencies"

[[exemptions.cc]]
version = "1.1.31"
criteria = "safe-to-run"

[[exemptions.cfg-expr]]
version = "0.17.0"
criteria = "safe-to-run"

[[exemptions.field-offset]]
version = "0.3.6"
criteria = "safe-to-run"

[[exemptions.futures-executor]]
version = "0.3.31"
criteria = "safe-to-run"

[[exemptions.gdk-pixbuf]]
version = "0.20.4"
criteria = "safe-to-run"
suggest = false
notes = "Do not audit gtk-rs itself, but just its dependencies"

[[exemptions.gdk-pixbuf-sys]]
version = "0.20.4"
criteria = "safe-to-run"
suggest = false
notes = "Do not audit gtk-rs itself, but just its dependencies"

[[exemptions.gdk4]]
version = "0.9.2"
criteria = "safe-to-run"
suggest = false
notes = "Do not audit gtk-rs itself, but just its dependencies"

[[exemptions.gdk4-sys]]
version = "0.9.2"
criteria = "safe-to-run"
suggest = false
notes = "Do not audit gtk-rs itself, but just its dependencies"

[[exemptions.gettext-rs]]
version = "0.7.2"
criteria = "safe-to-run"

[[exemptions.gettext-sys]]
version = "0.22.5"
criteria = "safe-to-run"

[[exemptions.gio]]
version = "0.20.4"
criteria = "safe-to-run"
suggest = false
notes = "Do not audit gtk-rs itself, but just its dependencies"

[[exemptions.gio-sys]]
version = "0.20.4"
criteria = "safe-to-run"
suggest = false
notes = "Do not audit gtk-rs itself, but just its dependencies"

[[exemptions.glib]]
version = "0.20.4"
criteria = "safe-to-run"
suggest = false
notes = "Do not audit gtk-rs itself, but just its dependencies"

[[exemptions.glib-macros]]
version = "0.20.4"
criteria = "safe-to-run"
suggest = false
notes = "Do not audit gtk-rs itself, but just its dependencies"

[[exemptions.glib-sys]]
version = "0.20.4"
criteria = "safe-to-run"
suggest = false
notes = "Do not audit gtk-rs itself, but just its dependencies"

[[exemptions.gobject-sys]]
version = "0.20.4"
criteria = "safe-to-run"
suggest = false
notes = "Do not audit gtk-rs itself, but just its dependencies"

[[exemptions.graphene-rs]]
version = "0.20.4"
criteria = "safe-to-run"
suggest = false
notes = "Do not audit gtk-rs itself, but just its dependencies"

[[exemptions.graphene-sys]]
version = "0.20.4"
criteria = "safe-to-run"
suggest = false
notes = "Do not audit gtk-rs itself, but just its dependencies"

[[exemptions.gsk4]]
version = "0.9.2"
criteria = "safe-to-run"
suggest = false
notes = "Do not audit gtk-rs itself, but just its dependencies"

[[exemptions.gsk4-sys]]
version = "0.9.2"
criteria = "safe-to-run"
suggest = false
notes = "Do not audit gtk-rs itself, but just its dependencies"

[[exemptions.gtk4]]
version = "0.9.2"
criteria = "safe-to-run"
suggest = false
notes = "Do not audit gtk-rs itself, but just its dependencies"

[[exemptions.gtk4-macros]]
version = "0.9.1"
criteria = "safe-to-run"
suggest = false
notes = "Do not audit gtk-rs itself, but just its dependencies"

[[exemptions.gtk4-sys]]
version = "0.9.2"
criteria = "safe-to-run"
suggest = false
notes = "Do not audit gtk-rs itself, but just its dependencies"

[[exemptions.hashbrown]]
version = "0.15.0"
criteria = "safe-to-run"

[[exemptions.indexmap]]
version = "2.6.0"
criteria = "safe-to-run"

[[exemptions.libadwaita]]
version = "0.7.0"
criteria = "safe-to-run"
suggest = false
notes = "Do not audit gtk-rs itself, but just its dependencies"

[[exemptions.libadwaita-sys]]
version = "0.7.0"
criteria = "safe-to-run"
suggest = false
notes = "Do not audit gtk-rs itself, but just its dependencies"

[[exemptions.libc]]
version = "0.2.161"
criteria = "safe-to-run"

[[exemptions.locale_config]]
version = "0.3.0"
criteria = "safe-to-run"

[[exemptions.memchr]]
version = "2.7.4"
criteria = "safe-to-run"

[[exemptions.memoffset]]
version = "0.9.1"
criteria = "safe-to-run"

[[exemptions.objc]]
version = "0.2.7"
criteria = "safe-to-run"

[[exemptions.objc-foundation]]
version = "0.1.1"
criteria = "safe-to-run"

[[exemptions.objc_id]]
version = "0.1.1"
criteria = "safe-to-run"

[[exemptions.pango]]
version = "0.20.4"
criteria = "safe-to-run"
suggest = false
notes = "Do not audit gtk-rs itself, but just its dependencies"

[[exemptions.pango-sys]]
version = "0.20.4"
criteria = "safe-to-run"
suggest = false
notes = "Do not audit gtk-rs itself, but just its dependencies"

[[exemptions.pin-project-lite]]
version = "0.2.15"
criteria = "safe-to-run"

[[exemptions.pkg-config]]
version = "0.3.31"
criteria = "safe-to-run"

[[exemptions.proc-macro-crate]]
version = "3.2.0"
criteria = "safe-to-run"

[[exemptions.serde]]
version = "1.0.213"
criteria = "safe-to-run"

[[exemptions.serde_derive]]
version = "1.0.213"
criteria = "safe-to-run"

[[exemptions.serde_spanned]]
version = "0.6.8"
criteria = "safe-to-run"

[[exemptions.slab]]
version = "0.4.9"
criteria = "safe-to-run"

[[exemptions.smallvec]]
version = "1.13.2"
criteria = "safe-to-run"

[[exemptions.syn]]
version = "2.0.85"
criteria = "safe-to-run"

[[exemptions.system-deps]]
version = "7.0.3"
criteria = "safe-to-run"

[[exemptions.target-lexicon]]
version = "0.12.16"
criteria = "safe-to-run"

[[exemptions.temp-dir]]
version = "0.1.14"
criteria = "safe-to-run"

[[exemptions.toml_edit]]
version = "0.22.22"
criteria = "safe-to-run"

[[exemptions.version-compare]]
version = "0.2.0"
criteria = "safe-to-run"

[[exemptions.winapi-i686-pc-windows-gnu]]
version = "0.4.0"
criteria = "safe-to-run"

[[exemptions.winapi-x86_64-pc-windows-gnu]]
version = "0.4.0"
criteria = "safe-to-run"

[[exemptions.windows-sys]]
version = "0.52.0"
criteria = "safe-to-run"

[[exemptions.windows-targets]]
version = "0.52.6"
criteria = "safe-to-run"

[[exemptions.windows_aarch64_gnullvm]]
version = "0.52.6"
criteria = "safe-to-run"

[[exemptions.windows_aarch64_msvc]]
version = "0.52.6"
criteria = "safe-to-run"

[[exemptions.windows_i686_gnu]]
version = "0.52.6"
criteria = "safe-to-run"

[[exemptions.windows_i686_gnullvm]]
version = "0.52.6"
criteria = "safe-to-run"

[[exemptions.windows_i686_msvc]]
version = "0.52.6"
criteria = "safe-to-run"

[[exemptions.windows_x86_64_gnu]]
version = "0.52.6"
criteria = "safe-to-run"

[[exemptions.windows_x86_64_gnullvm]]
version = "0.52.6"
criteria = "safe-to-run"

[[exemptions.windows_x86_64_msvc]]
version = "0.52.6"
criteria = "safe-to-run"

[[exemptions.winnow]]
version = "0.6.20"
criteria = "safe-to-run"
